title: GS E&C - HACKATHON　
title_1: GS E&C - SUSTAINABLE HACKATHON
email: dhkim21@gsenc.com  
description: |
  Open Innovation과 Design Thinking을 시작으로
  편견과 관념을 넘어 도전과 변화로 스스로의 성장을 이뤄갑니다.
baseurl:
url: 'https://gsenc-hackathon.github.io'
timezone: Asia/Seoul 

repository: GSENC-HACKATHON/GSENC-HACKATHON.github.io

permalink: /posts/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 11
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# Alpha's custom
author: dhkim21@gsenc.com
image: '/assets/images/green_cover_2A.jpg'
asset_url: /assets
google_analytics:
  ua: 'UA-148231208-1'
facebook:
  app_id: '-'
  username: '-'
twitter:
  username: '-'
instagram:
  username: '-'
github_url:
  username: '-'
